"""
make_sample_output.py — regenerate SAMPLE_OUTPUT.md.

Runs every calculation set on the current params.yaml and writes the results
table and the full working for each into SAMPLE_OUTPUT.md.

    python make_sample_output.py
"""

import os

import calculations
import parameters

HERE = os.path.dirname(__file__)
DEST = os.path.join(HERE, "SAMPLE_OUTPUT.md")


def build():
    params = parameters.load()
    flat = parameters.resolve(params)

    lines = [
        "# Sample output - every calculation set",
        "",
        "Generated by `make_sample_output.py`, running each set on the default "
        "`params.yaml` (BeetleBot seed values). Reproduce in the app with "
        "`python main.py` -> *Calculation sets* -> pick a set -> "
        "*View results with full working*.",
        "",
        "The parameter values used:",
        "",
        "```",
    ]
    width = max(len(k) for k in params)
    for key, spec in params.items():
        flag = "  <- confirm" if spec.get("confirm") else ""
        lines.append(f"  {key:<{width}} = {str(spec['value']):>10}  "
                     f"{spec.get('unit', ''):<8} {spec.get('desc', '')}{flag}")
    lines.append("```")
    lines.append("")

    for calc in calculations.CALCS:
        result = calc.fn(flat)
        lines += [
            f"## {calc.id} - {result.title}",
            "",
            f"*Parameters used: {', '.join(calc.uses)}*",
            "",
            "### Results only",
            "",
            "```",
            calculations.render_answer(result),
            "```",
            "",
            "### Results with full working",
            "",
            "```",
            calculations.render_steps(result),
            "```",
            "",
        ]

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    with open(DEST, "w", encoding="utf-8", newline="\n") as f:
        f.write(build())
    print(f"wrote {DEST}")
